sudo: false

language: node_js
node_js:
  - 8

branches:
  only:
    - integration
    - master
    - gh-pages
    - /(\d+\.)?(\d+\.)?(\*|\d+)/ # for tags

before_deploy:
  - npm install
  - npm run build

deploy:
  # push latest style guide to github pages
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    keep_history: true
    local_dir: build
    on:
      tags: true # will trigger on a github release
